/**********************************************************************************************************************
 * Copyright (c) 2015. Lorem ipsum dolor sit amet, consectetur adipiscing elit.                                       *
 * Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.                        *
 * Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.                                                   *
 * Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.                     *
 * Vestibulum commodo. Ut rhoncus gravida arcu.                                                                       *
 **********************************************************************************************************************/

package com.zy.cache.dao;

import com.zy.cache.entity.MerchantUrlIpEntity;

import java.util.List;

public interface MerchantUrlIpMapper
{
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table merchant_url_ip
	 *
	 * @mbggenerated
	 */
	List<MerchantUrlIpEntity> selectAll();

}
