package com.zy.cache.dao;

import com.zy.cache.entity.MerchantAccountEntity;

import java.util.List;

public interface MerchantAccountEntityMapper
{

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table merchant_account
	 *
	 * @mbggenerated
	 */
	List<MerchantAccountEntity> selectAllAccount();

}
